#!/usr/bin/env node
// Generate a barrel src/index.ts that re-exports every generated type.
// Idempotent — safe to run on every regen.
import { readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = new URL('../src/', import.meta.url).pathname;

/** @returns {string[]} */
function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    if (entry === 'index.ts') continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
    } else if (entry.endsWith('.ts')) {
      out.push(full);
    }
  }
  return out;
}

// Codex emits a root-level type AND a v2/ counterpart for some symbols.
// Prefer v2 when both exist — that's the surface we target.
const v2Names = new Set();
const allPaths = walk(ROOT).map((f) =>
  relative(ROOT, f).replace(/\.ts$/, '').replace(/\\/g, '/'),
);
for (const p of allPaths) {
  if (p.startsWith('v2/')) v2Names.add(p.slice('v2/'.length));
}
const keep = allPaths.filter((p) => {
  if (p.startsWith('v2/')) return true;
  return !v2Names.has(p);
});
const files = keep.map((p) => './' + p).sort();

const lines = [
  '// AUTO-GENERATED by scripts/make-index.mjs — do not edit.',
  '// Re-exports every generated codex app-server type.',
  '// When a symbol exists both at root and under v2/, the v2/ version wins.',
  '',
  ...files.map((f) => `export type * from '${f}';`),
  '',
];

writeFileSync(join(ROOT, 'index.ts'), lines.join('\n'));
console.log(`wrote barrel with ${files.length} re-exports`);
