#!/usr/bin/env python3
"""
Convert the source pet-art PNGs into LVGL v9 ``lv_image_dsc_t`` C arrays
ready to link into the firmware.

Pipeline per sprite:
    PNG (RGBA, large source res)
        ↓ resize (Lanczos) to target device-side dimensions
        ↓ split RGBA → (RGB565 plane | A8 plane)
        ↓ emit packed bytes as a ``uint8_t[]`` C array
        ↓ wrap in an ``lv_image_dsc_t`` declaration

The firmware ``CMakeLists.txt`` is regenerated to pick the .c files up
automatically (the generated files live under ``main/pet_art/`` so we
can ``GLOB`` them safely).

Run:

    python3 scripts/build_pet_art.py

Idempotent — re-running overwrites generated files. Source is
``packages/simulator/public/pet-art/``.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install pillow")

ROOT       = Path(__file__).resolve().parent.parent
SRC_DIR    = ROOT / "packages" / "simulator" / "public" / "pet-art"
DST_DIR    = ROOT / "packages" / "firmware" / "main" / "pet_art"
HEADER     = DST_DIR / "pet_art.h"


@dataclass(frozen=True)
class Sprite:
    """One sprite entry — source PNG → device-side target dimensions."""
    src:    str              # filename under SRC_DIR
    name:   str              # C symbol (e.g. "doudou_body")
    w:      int              # target width in pixels
    h:      int              # target height in pixels


# Display target = 240×240 round LCD. Sizes tuned to fit the circular
# safe area (~218×218) and keep total flash footprint reasonable.
SPRITES: list[Sprite] = [
    # Aspect ratios MUST match the source PNGs or the rendered sprite
    # gets squished. All source PNGs are 1254×1254 (1:1) except mouth_*
    # which are 1536×1024 (3:2).

    # Body: square so it stays the round shape the artist drew (not the
    # squat oval we got from a 1.36:1 target). 200×200 fits inside the
    # 240×240 round screen with a 20px margin on each side.
    Sprite("pet_body_glossy.png", "doudou_body_glossy",  200, 200),

    # Eyes — square sources, keep square.
    Sprite("eye_normal.png",   "doudou_eye_normal",   48, 48),
    Sprite("eye_blink.png",    "doudou_eye_blink",    48, 48),
    Sprite("eye_sleep.png",    "doudou_eye_sleep",    48, 48),
    Sprite("eye_x.png",        "doudou_eye_x",        48, 48),
    Sprite("eye_happy.png",    "doudou_eye_happy",    48, 48),
    Sprite("eye_surprise.png", "doudou_eye_surprise", 32, 32),

    # Mouth sources are 3:2 — render at 48×32 to keep that ratio.
    Sprite("mouth_smile.png",  "doudou_mouth_smile",  48, 32),
    Sprite("mouth_open.png",   "doudou_mouth_open",   48, 32),
    Sprite("mouth_grin.png",   "doudou_mouth_grin",   48, 32),
    Sprite("mouth_wobble.png", "doudou_mouth_wobble", 48, 32),
    Sprite("mouth_sad.png",    "doudou_mouth_sad",    48, 32),

    # Cheek source is 1:1.
    Sprite("cheek.png", "doudou_cheek", 24, 24),

    # floating accessories
    Sprite("acc_question.png", "doudou_acc_question", 48, 48),
    Sprite("acc_gear.png",     "doudou_acc_gear",     48, 48),
    Sprite("acc_sparkle.png",  "doudou_acc_sparkle",  48, 48),
    Sprite("acc_zzz.png",      "doudou_acc_zzz",      48, 48),
    Sprite("acc_sweat.png",    "doudou_acc_sweat",    48, 48),
    Sprite("acc_alert.png",    "doudou_acc_alert",    48, 48),
]


def rgb_to_rgb565(r: int, g: int, b: int) -> int:
    """Pack 8-8-8 RGB into 5-6-5 little-endian short."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def encode_rgb565a8(img: Image.Image) -> bytes:
    """
    LVGL ``LV_COLOR_FORMAT_RGB565A8`` layout: full RGB565 plane in
    row-major order, immediately followed by full A8 plane. Both planes
    are width × height; for RGB565 each pixel is 2 bytes (little-endian).
    """
    w, h = img.size
    px = img.load()
    rgb_buf = bytearray(w * h * 2)
    a_buf   = bytearray(w * h)
    i = 0
    j = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            v = rgb_to_rgb565(r, g, b)
            rgb_buf[i]   = v & 0xFF
            rgb_buf[i+1] = (v >> 8) & 0xFF
            a_buf[j]     = a
            i += 2
            j += 1
    return bytes(rgb_buf) + bytes(a_buf)


def chunks(seq: bytes, n: int) -> Iterable[bytes]:
    for i in range(0, len(seq), n):
        yield seq[i:i+n]


def write_sprite_c(sprite: Sprite, data: bytes) -> Path:
    """Emit one .c file with the byte array + lv_image_dsc_t struct."""
    out = DST_DIR / f"{sprite.name}.c"
    sym_data = f"{sprite.name}_data"
    stride_b = sprite.w * 2   # RGB565 row stride in bytes

    with out.open("w") as f:
        f.write(f"/* AUTO-GENERATED by scripts/build_pet_art.py — DO NOT EDIT. */\n")
        f.write(f"/* Source: packages/simulator/public/pet-art/{sprite.src} */\n")
        f.write(f"/* Format: LV_COLOR_FORMAT_RGB565A8  ({sprite.w}x{sprite.h}) */\n\n")
        f.write('#include "lvgl.h"\n\n')

        # Byte array
        f.write(f"static const LV_ATTRIBUTE_LARGE_CONST uint8_t {sym_data}[] = {{\n")
        for line in chunks(data, 16):
            f.write("    " + ", ".join(f"0x{b:02x}" for b in line) + ",\n")
        f.write("};\n\n")

        # Descriptor
        f.write(f"const lv_image_dsc_t {sprite.name} = {{\n")
        f.write(f"    .header.magic  = LV_IMAGE_HEADER_MAGIC,\n")
        f.write(f"    .header.cf     = LV_COLOR_FORMAT_RGB565A8,\n")
        f.write(f"    .header.flags  = 0,\n")
        f.write(f"    .header.w      = {sprite.w},\n")
        f.write(f"    .header.h      = {sprite.h},\n")
        f.write(f"    .header.stride = {stride_b},\n")
        f.write(f"    .data_size     = sizeof({sym_data}),\n")
        f.write(f"    .data          = {sym_data},\n")
        f.write("};\n")

    return out


def write_header(sprites: list[Sprite]) -> None:
    with HEADER.open("w") as f:
        f.write("/* AUTO-GENERATED by scripts/build_pet_art.py — DO NOT EDIT. */\n")
        f.write("/* Externs for every Doudou sprite image_dsc.            */\n\n")
        f.write("#pragma once\n\n")
        f.write('#include "lvgl.h"\n\n')
        f.write("#ifdef __cplusplus\n")
        f.write('extern "C" {\n')
        f.write("#endif\n\n")
        for s in sprites:
            f.write(f"extern const lv_image_dsc_t {s.name};   /* {s.w}x{s.h}  */\n")
        f.write("\n#ifdef __cplusplus\n")
        f.write("}\n")
        f.write("#endif\n")


def main() -> None:
    DST_DIR.mkdir(parents=True, exist_ok=True)

    # Clean stale .c files first (sprite list may have changed across runs)
    for f in DST_DIR.glob("*.c"):
        f.unlink()

    total_bytes = 0
    print(f"src: {SRC_DIR}")
    print(f"dst: {DST_DIR}")
    print()
    print(f"  {'sprite':<28s} {'WxH':>10s} {'bytes':>10s}")
    print(f"  {'-'*28} {'-'*10} {'-'*10}")

    for s in SPRITES:
        src_path = SRC_DIR / s.src
        if not src_path.exists():
            print(f"  {s.name:<28s} MISSING SOURCE: {src_path}")
            continue
        img = Image.open(src_path).convert("RGBA").resize(
            (s.w, s.h), Image.LANCZOS
        )
        data = encode_rgb565a8(img)
        write_sprite_c(s, data)
        total_bytes += len(data)
        print(f"  {s.name:<28s} {s.w}x{s.h:<8d} {len(data):>10d}")

    write_header(SPRITES)
    print()
    print(f"total raw sprite bytes: {total_bytes:,}  ({total_bytes / 1024:.1f} KB)")
    print(f"wrote {len(SPRITES)} .c files + pet_art.h")


if __name__ == "__main__":
    main()
