/* AUTO-GENERATED by scripts/build_pet_art.py — DO NOT EDIT. */
/* Externs for every Doudou sprite image_dsc.            */

#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t doudou_body_glossy;   /* 200x200  */
extern const lv_image_dsc_t doudou_eye_normal;   /* 48x48  */
extern const lv_image_dsc_t doudou_eye_blink;   /* 48x48  */
extern const lv_image_dsc_t doudou_eye_sleep;   /* 48x48  */
extern const lv_image_dsc_t doudou_eye_x;   /* 48x48  */
extern const lv_image_dsc_t doudou_eye_happy;   /* 48x48  */
extern const lv_image_dsc_t doudou_eye_surprise;   /* 32x32  */
extern const lv_image_dsc_t doudou_mouth_smile;   /* 48x32  */
extern const lv_image_dsc_t doudou_mouth_open;   /* 48x32  */
extern const lv_image_dsc_t doudou_mouth_grin;   /* 48x32  */
extern const lv_image_dsc_t doudou_mouth_wobble;   /* 48x32  */
extern const lv_image_dsc_t doudou_mouth_sad;   /* 48x32  */
extern const lv_image_dsc_t doudou_cheek;   /* 24x24  */
extern const lv_image_dsc_t doudou_acc_question;   /* 48x48  */
extern const lv_image_dsc_t doudou_acc_gear;   /* 48x48  */
extern const lv_image_dsc_t doudou_acc_sparkle;   /* 48x48  */
extern const lv_image_dsc_t doudou_acc_zzz;   /* 48x48  */
extern const lv_image_dsc_t doudou_acc_sweat;   /* 48x48  */
extern const lv_image_dsc_t doudou_acc_alert;   /* 48x48  */

#ifdef __cplusplus
}
#endif
